common:
  env: prd
  ingress:
    host: poiman.entur.io
    trafficType: public
  deployment:
    minReplicas: 2
    maxReplicas: 10
  configmap:
    data:
      OIDC_AUTHORITY: https://partner.entur.org
      OIDC_AUDIENCE: https://api.entur.io
