common:
  env: prd
  ingress:
    host: poiman.entur.io
    trafficType: api
  replicas: 2
  configmap:
    data:
      OIDC_AUTHORITY: https://partner.entur.org
      OIDC_CLIENT_ID: ""
      OIDC_AUDIENCE: https://api.entur.io
