common:
  env: dev
  ingress:
    host: poiman.dev.entur.io
    trafficType: public
  configmap:
    data:
      OIDC_AUTHORITY: https://partner.dev.entur.org
      OIDC_AUDIENCE: https://api.dev.entur.io
