common:
  env: tst
  ingress:
    host: poiman.staging.entur.io
    trafficType: public
  configmap:
    data:
      OIDC_AUTHORITY: https://partner.staging.entur.org
      OIDC_AUDIENCE: https://api.staging.entur.io
